[Metadata]
Name=Matugen
Version=0.1
Author=shorin
Description=WallpaperColorSyncByMatugen
ScaleWithDPI=True

[InputPanel]
NormalColor={{colors.on_surface.default.hex}}
HighlightColor={{colors.on_primary.default.hex}}
HighlightBackgroundColor={{colors.tertiary.default.hex}}
HighlightCandidateColor={{colors.on_tertiary.default.hex}}
EnableBlur=False
FullWidthHighlight=True
PageButtonAlignment="Last Candidate"

[InputPanel/Background]
Color={{colors.surface_container.default.hex}}
BorderColor={{colors.outline.default.hex}}
BorderWidth=2

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color={{colors.tertiary.default.hex}}

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor={{colors.on_surface.default.hex}}
HighlightCandidateColor={{colors.on_surface.default.hex}}

[Menu/Background]
Color={{colors.surface_container.default.hex}}
BorderColor={{colors.outline.default.hex}}
BorderWidth=2

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color={{colors.tertiary.default.hex}}
BorderColor={{colors.outline.default.hex}}
BorderWidth=0

[Menu/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
